#!/bin/sh

# List articles in chronological order and upon selection open them in pdf reader
articledir=$HOME/doc/article/
articlename=$(find $articledir -type f -printf '%T@ %p\n' | sort -nr | sed 's|^[0-9]*\.[0-9]* ||g' | sed "s|$articledir||g" | fzf --height 40% --reverse --exact)
if [ -n "$articlename" ]; then zathura --fork "$articledir$articlename" &>/dev/null ; fi
