#!/bin/bash

# List all notebooks in a fzf finder then run it in browser
# Runnig by default in server with port 8888. If there are multiple running servers the port is different! 
# Run this after invoking the appropriate jupyter notebook server with the `notebook` script
notebookdir=$HOME/dev/notebook/
notebook_path=$(find -L $notebookdir -name '*.ipynb' -type f -printf '%T@ %p\n' | sort -nr | sed 's|^[0-9]*\.[0-9]* ||g' | sed "s|$HOME/||g" | grep -v '.ipynb_checkpoints' | fzf --height 40% --reverse | sed "s|$HOME/||g")
firefox "http://localhost:8888/notebooks/$notebook_path" &>/dev/null
# brave localhost:8888/notebooks/"$notebook_path"
# surf localhost:8888/notebooks/"$notebook_path"
