#!/bin/sh

# Search and open one of the config files or custom scripts

# { find ~/.scripts ~/.config -type f ; find ~ -maxdepth 1 -type f ; } | sed "s|$HOME/||g" | fzf --height 40% --reverse | xargs -r -I {} subl $HOME/{}
filename=$({ find ~/.scripts ~/.config -type f -printf '%T@ %p\n' | sort -nr | sed 's|^[0-9]*\.[0-9]* ||g' ; find ~ -maxdepth 1 -type f -printf '%T@ %p\n' | sort -nr | sed 's|^[0-9]*\.[0-9]* ||g' ; } | sed "s|$HOME/||g" | fzf --height 40% --reverse)
if [ -n "$filename" ]; then vim $HOME/"$filename"; fi
